int_libs = # Interface dependencies.
imp_libs = # Implementation dependencies.
#import imp_libs += libhello%lib{hello}

lib{inbug2}: {hxx ixx txx cxx}{** -version} hxx{version} $imp_libs $int_libs
lib{inbug2}: hxx{bug}

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
hxx{version}:
{
  dist  = true
  clean = ($src_root != $out_root)
}

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.poptions += "-I$out_base" # This is to allow including bug.hxx which is generated in out_base

obja{*}: cxx.poptions += -DINBUG2_STATIC_BUILD
objs{*}: cxx.poptions += -DINBUG2_SHARED_BUILD

# Export options.
#
lib{inbug2}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $int_libs
}

liba{inbug2}: cxx.export.poptions += -DINBUG2_STATIC
libs{inbug2}: cxx.export.poptions += -DINBUG2_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{inbug2}: bin.lib.version = @"-$version.project_id"
else
  lib{inbug2}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the inbug2/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/inbug2/
  install.subdirs = true
}


hxx{bug}: bug/in{bug}

